package com.iamsystem.service;

import java.util.Map;

import org.springframework.stereotype.Service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

@Service
public class CLMService {

	public Map<String,Object> getUserData(){
		
		String userdata = userDataJson();
		 Map<String,Object> result = convertStringToMap(userdata);
		 return result;
	}
	
	public Map<String, Object> convertStringToMap(String data) {
		ObjectMapper mapper = new ObjectMapper();
		Map<String, Object> map = null;
		try {
			map = mapper.readValue(data, new TypeReference<Map<String, Object>>() {});
		} catch (JsonMappingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return map;
	}

	private String userDataJson() {
		String data = "{\r\n"
				+ "    \"records\": [\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Apr 13 2025 04:25:42\",\r\n"
				+ "            \"last_name\": \"Admin\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Clause Library Manager\",\r\n"
				+ "                \"Compliance Team approver\",\r\n"
				+ "                \"Contract Creator\",\r\n"
				+ "                \"Finance Team Approver\",\r\n"
				+ "                \"Internal Signer for contracts\",\r\n"
				+ "                \"Legal Team Approver\",\r\n"
				+ "                \"Project Manager\",\r\n"
				+ "                \"Risk Approval team for contracts\",\r\n"
				+ "                \"Internal Supplier Manager\",\r\n"
				+ "                \"Business Admin\",\r\n"
				+ "                \"admin\",\r\n"
				+ "                \"Contract Requester\",\r\n"
				+ "                \"Executive Team\",\r\n"
				+ "                \"Sourcing Event Requester\",\r\n"
				+ "                \"Sourcing Event Creator\",\r\n"
				+ "                \"Sourcing Event Manager\",\r\n"
				+ "                \"Evaluation Committee\",\r\n"
				+ "                \"Budget Manager\",\r\n"
				+ "                \"Legal Requester\",\r\n"
				+ "                \"Legal Request/Matter Manager\",\r\n"
				+ "                \"Patent Legal Team\",\r\n"
				+ "                \"Litigation Legal Team\",\r\n"
				+ "                \"Trademark Legal Team\",\r\n"
				+ "                \"Supplier Evaluator\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Agiloft\",\r\n"
				+ "            \"email\": \"1admin@example.com\",\r\n"
				+ "            \"_login\": \"1admin\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 213\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 14 2025 09:04:56\",\r\n"
				+ "            \"last_name\": \"Suzuki\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"John\",\r\n"
				+ "            \"email\": \"1example@example.com\",\r\n"
				+ "            \"_login\": \"1customer\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 250\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 21 2025 04:39:18\",\r\n"
				+ "            \"last_name\": null,\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Clause Library Manager\",\r\n"
				+ "                \"Compliance Team approver\",\r\n"
				+ "                \"Contract Creator\",\r\n"
				+ "                \"Finance Team Approver\",\r\n"
				+ "                \"Internal Signer for contracts\",\r\n"
				+ "                \"Legal Team Approver\",\r\n"
				+ "                \"Project Manager\",\r\n"
				+ "                \"Risk Approval team for contracts\",\r\n"
				+ "                \"Internal Supplier Manager\",\r\n"
				+ "                \"Business Admin\",\r\n"
				+ "                \"admin\",\r\n"
				+ "                \"Contract Requester\",\r\n"
				+ "                \"Executive Team\",\r\n"
				+ "                \"Sourcing Event Requester\",\r\n"
				+ "                \"Sourcing Event Creator\",\r\n"
				+ "                \"Sourcing Event Manager\",\r\n"
				+ "                \"Evaluation Committee\",\r\n"
				+ "                \"Budget Manager\",\r\n"
				+ "                \"Legal Requester\",\r\n"
				+ "                \"Legal Request/Matter Manager\",\r\n"
				+ "                \"Patent Legal Team\",\r\n"
				+ "                \"Litigation Legal Team\",\r\n"
				+ "                \"Trademark Legal Team\",\r\n"
				+ "                \"Supplier Evaluator\",\r\n"
				+ "                \"Reviewer\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"EWSystem\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1ewsystem\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 351\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 09:43:13\",\r\n"
				+ "            \"last_name\": null,\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Clause Library Manager\",\r\n"
				+ "                \"Compliance Team approver\",\r\n"
				+ "                \"Contract Creator\",\r\n"
				+ "                \"Finance Team Approver\",\r\n"
				+ "                \"Internal Signer for contracts\",\r\n"
				+ "                \"Legal Team Approver\",\r\n"
				+ "                \"Project Manager\",\r\n"
				+ "                \"Risk Approval team for contracts\",\r\n"
				+ "                \"Internal Supplier Manager\",\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"System\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1system\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 394\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 15 2025 18:03:45\",\r\n"
				+ "            \"last_name\": \"Barash\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Risk Approval team for contracts\",\r\n"
				+ "                \"Finance Team Approver\",\r\n"
				+ "                \"Internal Signer for contracts\",\r\n"
				+ "                \"Compliance Team approver\",\r\n"
				+ "                \"Legal Team Approver\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Robert\",\r\n"
				+ "            \"email\": \"1example8@example.com\",\r\n"
				+ "            \"_login\": \"1contractmgr\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 397\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 15 2025 17:47:13\",\r\n"
				+ "            \"last_name\": \"Teller\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Legal Team Approver\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Denise\",\r\n"
				+ "            \"email\": \"1legal@example.com\",\r\n"
				+ "            \"_login\": \"1contractapprover\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 399\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 21 2025 20:43:46\",\r\n"
				+ "            \"last_name\": \"Jensen\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Internal Signer for contracts\",\r\n"
				+ "                \"Contract Creator\",\r\n"
				+ "                \"Supplier Evaluator\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Helen\",\r\n"
				+ "            \"email\": \"1example32@example.com\",\r\n"
				+ "            \"_login\": \"1contractuser\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 431\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jul 09 2025 17:55:40\",\r\n"
				+ "            \"last_name\": \"Admin\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Internal Signer for contracts\",\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Business\",\r\n"
				+ "            \"email\": \"1example5@example.com\",\r\n"
				+ "            \"_login\": \"1busadmin\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 434\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 14:19:07\",\r\n"
				+ "            \"last_name\": \"Sendak\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Maurice\",\r\n"
				+ "            \"email\": \"1example35@example.com\",\r\n"
				+ "            \"_login\": \"1msendak\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 437\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 15 2025 17:46:28\",\r\n"
				+ "            \"last_name\": \"Johnson\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Michael\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1iversonuser2\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 439\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 15 2025 17:46:28\",\r\n"
				+ "            \"last_name\": \"Dupont\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Cathy\",\r\n"
				+ "            \"email\": \"1c.dupont@example.com\",\r\n"
				+ "            \"_login\": \"1cdupont\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 441\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 15 2025 17:47:13\",\r\n"
				+ "            \"last_name\": \"Steinwort\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Finance Team Approver\",\r\n"
				+ "                \"Compliance Team approver\",\r\n"
				+ "                \"Contract Creator\",\r\n"
				+ "                \"Budget Manager\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"John\",\r\n"
				+ "            \"email\": \"1example41@example.com\",\r\n"
				+ "            \"_login\": \"1finance\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 449\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 16:34:20\",\r\n"
				+ "            \"last_name\": \"Ocasek\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Ezekiel\",\r\n"
				+ "            \"email\": \"1zekeo@example.com\",\r\n"
				+ "            \"_login\": \"1zekeo@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 455\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 17 2025 19:29:46\",\r\n"
				+ "            \"last_name\": \"Wilson\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Amelia\",\r\n"
				+ "            \"email\": \"1Awilson@example.com\",\r\n"
				+ "            \"_login\": \"1Awilson@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 456\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 16:27:52\",\r\n"
				+ "            \"last_name\": \"Federer\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Rosie\",\r\n"
				+ "            \"email\": \"1Rosief@example.com\",\r\n"
				+ "            \"_login\": \"1Rosief@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 457\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 19 2025 09:18:12\",\r\n"
				+ "            \"last_name\": \"Kindle\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Verity\",\r\n"
				+ "            \"email\": \"1veritas@example.com\",\r\n"
				+ "            \"_login\": \"1veritas@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 458\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 14 2025 09:04:53\",\r\n"
				+ "            \"last_name\": \"Ruiz\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Zenobia\",\r\n"
				+ "            \"email\": \"1zruiz@example.com\",\r\n"
				+ "            \"_login\": \"1zruiz@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 459\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 14 2025 09:04:53\",\r\n"
				+ "            \"last_name\": \"Stiles\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"William\",\r\n"
				+ "            \"email\": \"1bstiles@example.com\",\r\n"
				+ "            \"_login\": \"1bstiles@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 460\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 16:24:19\",\r\n"
				+ "            \"last_name\": \"Freund\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Hilton\",\r\n"
				+ "            \"email\": \"1hill@example.com\",\r\n"
				+ "            \"_login\": \"1hill@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 461\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 16:23:08\",\r\n"
				+ "            \"last_name\": \"Parks\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Kenneth\",\r\n"
				+ "            \"email\": \"1kenp@example.org\",\r\n"
				+ "            \"_login\": \"1kenp@example.org\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 462\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 16:21:08\",\r\n"
				+ "            \"last_name\": \"Epps\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Charles\",\r\n"
				+ "            \"email\": \"1charliee@example.com\",\r\n"
				+ "            \"_login\": \"1charliee@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 463\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 10 2025 22:15:01\",\r\n"
				+ "            \"last_name\": \"Thomasson\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Humphrey\",\r\n"
				+ "            \"email\": \"1humpt@example.com\",\r\n"
				+ "            \"_login\": \"1humpt@xample.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 464\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 16:16:04\",\r\n"
				+ "            \"last_name\": \"Delphos\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Athena\",\r\n"
				+ "            \"email\": \"1TinaD@example.com\",\r\n"
				+ "            \"_login\": \"1TinaD@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 465\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 10 2025 22:14:51\",\r\n"
				+ "            \"last_name\": \"Whitemountain\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Barbara\",\r\n"
				+ "            \"email\": \"1bwhitemountain@example.com\",\r\n"
				+ "            \"_login\": \"1bwhitemountain@xample.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 466\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 14 2025 09:04:52\",\r\n"
				+ "            \"last_name\": \"Newman\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Rickie\",\r\n"
				+ "            \"email\": \"1rickien@example.com\",\r\n"
				+ "            \"_login\": \"1rickien@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 467\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 14 2025 09:04:52\",\r\n"
				+ "            \"last_name\": \"Petit\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Gerard\",\r\n"
				+ "            \"email\": \"1gpetit@example.com\",\r\n"
				+ "            \"_login\": \"1gpetit@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 468\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 10 2025 22:14:47\",\r\n"
				+ "            \"last_name\": \"Sanchez\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Delilah\",\r\n"
				+ "            \"email\": \"1Dsanchez@example.com\",\r\n"
				+ "            \"_login\": \"1Dsanchez@eee.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 469\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 14:59:12\",\r\n"
				+ "            \"last_name\": \"DiSabato\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Innocent\",\r\n"
				+ "            \"email\": \"1innods@example.com\",\r\n"
				+ "            \"_login\": \"1innods@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 470\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 14 2025 09:04:52\",\r\n"
				+ "            \"last_name\": \"Wambaugh\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Evelyn\",\r\n"
				+ "            \"email\": \"1ewambaugh@example.com\",\r\n"
				+ "            \"_login\": \"1ewambaugh@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 471\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 12:19:43\",\r\n"
				+ "            \"last_name\": \"Smith\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Sam\",\r\n"
				+ "            \"email\": \"1supplieruser@example.com\",\r\n"
				+ "            \"_login\": \"1supplieruser\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 474\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 14 2025 09:04:51\",\r\n"
				+ "            \"last_name\": \"Jones\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Johnson\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1475\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 475\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 26 2025 16:32:31\",\r\n"
				+ "            \"last_name\": \"Lee\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Requester\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Christopher\",\r\n"
				+ "            \"email\": \"1contractreq@example.com\",\r\n"
				+ "            \"_login\": \"1contractreq\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 476\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 09 2025 09:37:22\",\r\n"
				+ "            \"last_name\": \"Adams\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Douglas\",\r\n"
				+ "            \"email\": \"1douglas.adams@example.com\",\r\n"
				+ "            \"_login\": \"1douglas.adams@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 477\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 17:13:00\",\r\n"
				+ "            \"last_name\": \"Myers\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Georgia\",\r\n"
				+ "            \"email\": \"1gmyers@example.com\",\r\n"
				+ "            \"_login\": \"1gmyers@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 479\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 20:01:12\",\r\n"
				+ "            \"last_name\": \"Gibbs\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Marsha\",\r\n"
				+ "            \"email\": \"1mgibbstesla@example.com\",\r\n"
				+ "            \"_login\": \"1mgibbstesla@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 480\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 15 2025 17:47:12\",\r\n"
				+ "            \"last_name\": \"Shaw\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Executive Team\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Lauren\",\r\n"
				+ "            \"email\": \"1lauren.shaw@example.com\",\r\n"
				+ "            \"_login\": \"1cfoapprover\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 494\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 15 2025 17:47:13\",\r\n"
				+ "            \"last_name\": \"Allen\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Evaluation Committee\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Kelly\",\r\n"
				+ "            \"email\": \"1sourcingmgr@example.com\",\r\n"
				+ "            \"_login\": \"1sourcingmgr\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 496\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 20:01:02\",\r\n"
				+ "            \"last_name\": \"Brady\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Marcia\",\r\n"
				+ "            \"email\": \"1marcia@example.com\",\r\n"
				+ "            \"_login\": \"1marcia@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 510\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 04 2025 14:37:35\",\r\n"
				+ "            \"last_name\": \"Farnsworth\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Sourcing Event Creator\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Hubert\",\r\n"
				+ "            \"email\": \"1example42@example.com\",\r\n"
				+ "            \"_login\": \"1sourcingusr\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 514\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 02 2025 10:17:41\",\r\n"
				+ "            \"last_name\": \"Dent\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Sourcing Event Requester\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Arthur\",\r\n"
				+ "            \"email\": \"1example43@example.com\",\r\n"
				+ "            \"_login\": \"1sourcingreq\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 515\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 23 2025 07:06:51\",\r\n"
				+ "            \"last_name\": \"Rolling\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Legal Requester\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Jennifer\",\r\n"
				+ "            \"email\": \"1jennifer.rolling@example.com\",\r\n"
				+ "            \"_login\": \"1legalreq\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 622\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 23 2025 07:08:52\",\r\n"
				+ "            \"last_name\": \"Commings\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Legal Request/Matter Manager\",\r\n"
				+ "                \"Litigation Legal Team\",\r\n"
				+ "                \"Trademark Legal Team\",\r\n"
				+ "                \"Patent Legal Team\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Suzanne\",\r\n"
				+ "            \"email\": \"1suzanne.commings@example.com\",\r\n"
				+ "            \"_login\": \"1legalmgr\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 623\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 28 2025 07:18:15\",\r\n"
				+ "            \"last_name\": \"Brooks\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Budget Manager\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Henry\",\r\n"
				+ "            \"email\": \"1henry.brooks@example.com\",\r\n"
				+ "            \"_login\": \"1budgetmgr\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 624\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 18 2025 05:50:30\",\r\n"
				+ "            \"last_name\": \"Miller\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Internal Supplier Manager\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Vanessa\",\r\n"
				+ "            \"email\": \"1vanessa.miller@example.com\",\r\n"
				+ "            \"_login\": \"1suppliermgr\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 625\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 18:42:45\",\r\n"
				+ "            \"last_name\": \"Silverman\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Jason\",\r\n"
				+ "            \"email\": \"1jasonsilverman@example.com\",\r\n"
				+ "            \"_login\": \"1jasonsilverman\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 630\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 08 2025 17:49:44\",\r\n"
				+ "            \"last_name\": \"Martin\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Bob\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1bobmartin\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 631\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 08 2025 17:49:24\",\r\n"
				+ "            \"last_name\": \"Rapaport\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Charles\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1crapaport\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 634\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 06 2025 14:12:00\",\r\n"
				+ "            \"last_name\": \"Santos\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Gloria\",\r\n"
				+ "            \"email\": \"1gloria.santos@example.com\",\r\n"
				+ "            \"_login\": \"1gloria.santos@example.com\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 640\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 09 2025 20:05:15\",\r\n"
				+ "            \"last_name\": \"Hext\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Devan\",\r\n"
				+ "            \"email\": \"1devan.hext@example.com\",\r\n"
				+ "            \"_login\": \"1devanhext\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 642\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 07 2025 14:06:10\",\r\n"
				+ "            \"last_name\": \"Fisher\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": null,\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Jess\",\r\n"
				+ "            \"email\": \"1jessfisher@example.com\",\r\n"
				+ "            \"_login\": \"1jessfisher\",\r\n"
				+ "            \"employment_status\": null,\r\n"
				+ "            \"id\": 643\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 28 2025 11:20:35\",\r\n"
				+ "            \"last_name\": \"Rose\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Supplier Evaluator\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Katie\",\r\n"
				+ "            \"email\": \"1katie.rose@example.com\",\r\n"
				+ "            \"_login\": \"1supplierevaluator\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 662\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 24 2025 07:26:10\",\r\n"
				+ "            \"last_name\": \"Mercogliano\",\r\n"
				+ "            \"internal_id\": \"A3S2D1\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Paul\",\r\n"
				+ "            \"email\": \"1paulmisnotmyname@agiloft.com\",\r\n"
				+ "            \"_login\": \"1paulm\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 666\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jul 09 2025 22:55:32\",\r\n"
				+ "            \"last_name\": \"Clare\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\",\r\n"
				+ "                \"Business Admin\",\r\n"
				+ "                \"Finance Team Approver\",\r\n"
				+ "                \"Internal Signer for contracts\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Tom\",\r\n"
				+ "            \"email\": \"1thomas.j.clare@pwc.com\",\r\n"
				+ "            \"_login\": \"1thomas.j.clare@pwc.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 667\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 10 2025 08:19:03\",\r\n"
				+ "            \"last_name\": \"Liggett\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Gareth\",\r\n"
				+ "            \"email\": \"1gareth.liggett@pwc.com\",\r\n"
				+ "            \"_login\": \"1garethl\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 668\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 08 2025 13:40:12\",\r\n"
				+ "            \"last_name\": \"Felicio\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Olavio\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1olaviof\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 669\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Apr 23 2025 23:59:33\",\r\n"
				+ "            \"last_name\": \"Sarkar\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Rup\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1rups\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 670\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Apr 22 2025 04:29:01\",\r\n"
				+ "            \"last_name\": \"Mququ\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Axolile\",\r\n"
				+ "            \"email\": \"1axolile.mququ@pwc.com\",\r\n"
				+ "            \"_login\": \"1axolile.mququ@pwc.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 671\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 09:35:55\",\r\n"
				+ "            \"last_name\": \"Moepi\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Nombulelo\",\r\n"
				+ "            \"email\": \"1nombulelo.moepi@pwc.com\",\r\n"
				+ "            \"_login\": \"1nombulelo.moepi@pwc.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 672\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Apr 15 2025 04:55:04\",\r\n"
				+ "            \"last_name\": \"Mlambo\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Samantha\",\r\n"
				+ "            \"email\": \"1samantha.mlambo@pwc.com\",\r\n"
				+ "            \"_login\": \"1samantha.mlambo@pwc.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 673\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:35\",\r\n"
				+ "            \"last_name\": \"Khaw\",\r\n"
				+ "            \"internal_id\": \"KLAAK1\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Angeline\",\r\n"
				+ "            \"email\": \"1Angeline.Khaw@Shell.com\",\r\n"
				+ "            \"_login\": \"1Angeline.Khaw@Shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 674\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:35\",\r\n"
				+ "            \"last_name\": \"Yan\",\r\n"
				+ "            \"internal_id\": \"MYFYA0\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Foo-Kai\",\r\n"
				+ "            \"email\": \"1Foo-Kai.Yan@shell.com\",\r\n"
				+ "            \"_login\": \"1Foo-Kai.Yan@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 675\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:36\",\r\n"
				+ "            \"last_name\": \"Siow\",\r\n"
				+ "            \"internal_id\": \"MYKSJ9\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Kimberly\",\r\n"
				+ "            \"email\": \"1Kimberly.Siow@shell.com\",\r\n"
				+ "            \"_login\": \"1Kimberly.Siow@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 676\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:36\",\r\n"
				+ "            \"last_name\": \"Tan\",\r\n"
				+ "            \"internal_id\": \"MYMTAA\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Michelle\",\r\n"
				+ "            \"email\": \"1Michelle.C.T.Tan@shell.com\",\r\n"
				+ "            \"_login\": \"1Michelle.C.T.Tan@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 677\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 02 2025 09:30:43\",\r\n"
				+ "            \"last_name\": \"User\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Clause Library Manager\",\r\n"
				+ "                \"Compliance Team approver\",\r\n"
				+ "                \"Contract Creator\",\r\n"
				+ "                \"Finance Team Approver\",\r\n"
				+ "                \"Internal Signer for contracts\",\r\n"
				+ "                \"Legal Team Approver\",\r\n"
				+ "                \"Project Manager\",\r\n"
				+ "                \"Risk Approval team for contracts\",\r\n"
				+ "                \"Internal Supplier Manager\",\r\n"
				+ "                \"Business Admin\",\r\n"
				+ "                \"admin\",\r\n"
				+ "                \"Contract Requester\",\r\n"
				+ "                \"Executive Team\",\r\n"
				+ "                \"Sourcing Event Requester\",\r\n"
				+ "                \"Sourcing Event Creator\",\r\n"
				+ "                \"Sourcing Event Manager\",\r\n"
				+ "                \"Evaluation Committee\",\r\n"
				+ "                \"Budget Manager\",\r\n"
				+ "                \"Legal Requester\",\r\n"
				+ "                \"Legal Request/Matter Manager\",\r\n"
				+ "                \"Patent Legal Team\",\r\n"
				+ "                \"Litigation Legal Team\",\r\n"
				+ "                \"Trademark Legal Team\",\r\n"
				+ "                \"Supplier Evaluator\",\r\n"
				+ "                \"Reviewer\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"API\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1shellitapiuser\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 678\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Apr 20 2025 23:34:16\",\r\n"
				+ "            \"last_name\": \"Doe\",\r\n"
				+ "            \"internal_id\": \"FD23FR\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"John\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1jdoeH\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 680\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Apr 20 2025 23:38:16\",\r\n"
				+ "            \"last_name\": \"Doe\",\r\n"
				+ "            \"internal_id\": \"SDFi32\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Jane\",\r\n"
				+ "            \"email\": \"1jd@example.com\",\r\n"
				+ "            \"_login\": \"1jhDOE\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 681\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Apr 24 2025 05:53:16\",\r\n"
				+ "            \"last_name\": \"Templates\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"RupBA\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1RupBA\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 682\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Apr 24 2025 09:28:43\",\r\n"
				+ "            \"last_name\": \"Test\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"RupCMD\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1RupCMD\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 688\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Apr 28 2025 09:37:59\",\r\n"
				+ "            \"last_name\": \"Contract Manager\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Scale Up\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1Contract Manager Scale Up\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 689\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 10:34:55\",\r\n"
				+ "            \"last_name\": \"Test\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Manager\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"BA\",\r\n"
				+ "            \"email\": \"1gareth.liggett@uk.pwc.com\",\r\n"
				+ "            \"_login\": \"1BA Test\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 690\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 02 2025 10:18:51\",\r\n"
				+ "            \"last_name\": \"Test - TC\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"BA\",\r\n"
				+ "            \"email\": \"1testBaEmail@pwc.com\",\r\n"
				+ "            \"_login\": \"1Test BA\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 691\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:36\",\r\n"
				+ "            \"last_name\": \"Vadla\",\r\n"
				+ "            \"internal_id\": \"GBRVF8888888\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Creator\",\r\n"
				+ "                \"Contract Manager\",\r\n"
				+ "                \"Contract Requester\",\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Ravi\",\r\n"
				+ "            \"email\": \"1Ravi-Kumar.R.Vadla@shellnovmot.onmicrosoft.com\",\r\n"
				+ "            \"_login\": \"1Ravi-Kumar.R.Vadla@shellnovmot.onmicrosoft.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 693\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 03 2025 20:34:46\",\r\n"
				+ "            \"last_name\": \"Jerubandi\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Neeraja\",\r\n"
				+ "            \"email\": \"1Neeraja.Jerubandi@shellnovmot.onmicrosoft.com\",\r\n"
				+ "            \"_login\": \"1Neeraja.Jerubandi@shellnovmot.onmicrosoft.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 694\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 02 2025 12:50:01\",\r\n"
				+ "            \"last_name\": \"Vadla\",\r\n"
				+ "            \"internal_id\": \"GBRVF8\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Creator\",\r\n"
				+ "                \"Business Admin\",\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Ravi\",\r\n"
				+ "            \"email\": \"1Ravi-Kumar.R.Vadla@shell.com\",\r\n"
				+ "            \"_login\": \"1Ravi-Kumar.R.Vadla@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 695\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 10 2025 08:25:00\",\r\n"
				+ "            \"last_name\": \"Koseva\",\r\n"
				+ "            \"internal_id\": \"BGEKO0\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Ekaterina\",\r\n"
				+ "            \"email\": \"1Ekaterina.Koseva@shell.com\",\r\n"
				+ "            \"_login\": \"1Ekaterina.Koseva@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 749\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:36\",\r\n"
				+ "            \"last_name\": \"Federico\",\r\n"
				+ "            \"internal_id\": \"NLFSAN\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Salmoiraghi\",\r\n"
				+ "            \"email\": \"1F.Salmoiraghi@shell.com\",\r\n"
				+ "            \"_login\": \"1F.Salmoiraghi@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 750\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:36\",\r\n"
				+ "            \"last_name\": \"Ganesh\",\r\n"
				+ "            \"internal_id\": \"INGRCM\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"R\",\r\n"
				+ "            \"email\": \"1G.R@shell.com\",\r\n"
				+ "            \"_login\": \"1G.R@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 751\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:37\",\r\n"
				+ "            \"last_name\": \"Chong-Velea\",\r\n"
				+ "            \"internal_id\": \"NLGCHF\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Gabriela\",\r\n"
				+ "            \"email\": \"1Gabriela.Chong-Velea@shell.com\",\r\n"
				+ "            \"_login\": \"1Gabriela.Chong-Velea@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 752\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:37\",\r\n"
				+ "            \"last_name\": \"Pajak\",\r\n"
				+ "            \"internal_id\": \"PLJPA1\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Justyna\",\r\n"
				+ "            \"email\": \"1Justyna.Pajak@shell.com\",\r\n"
				+ "            \"_login\": \"1Justyna.Pajak@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 753\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 10 2025 08:25:00\",\r\n"
				+ "            \"last_name\": \"Pieta-Rydarowicz\",\r\n"
				+ "            \"internal_id\": \"PLKPID\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Katarzyna\",\r\n"
				+ "            \"email\": \"1K.Pieta-Rydarowicz@shell.com\",\r\n"
				+ "            \"_login\": \"1K.Pieta-Rydarowicz@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 754\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 10 2025 08:25:00\",\r\n"
				+ "            \"last_name\": \"Owsianka\",\r\n"
				+ "            \"internal_id\": \"PLKRO4\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Kamila\",\r\n"
				+ "            \"email\": \"1Kamila.Rosa@shell.com\",\r\n"
				+ "            \"_login\": \"1Kamila.Rosa@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 755\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:37\",\r\n"
				+ "            \"last_name\": \"vanderMolen\",\r\n"
				+ "            \"internal_id\": \"NLKVCD\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Kees-Jan\",\r\n"
				+ "            \"email\": \"1Kees-Jan.vanderMolen@shell.com\",\r\n"
				+ "            \"_login\": \"1Kees-Jan.vanderMolen@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 756\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:37\",\r\n"
				+ "            \"last_name\": \"Loong Lee\",\r\n"
				+ "            \"internal_id\": \"MYKLEK\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Kian\",\r\n"
				+ "            \"email\": \"1KianLoong.Lee@shell.com\",\r\n"
				+ "            \"_login\": \"1KianLoong.Lee@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 757\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:38\",\r\n"
				+ "            \"last_name\": \"Krishna\",\r\n"
				+ "            \"internal_id\": \"INKCIY\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Chaitanya\",\r\n"
				+ "            \"email\": \"1Krishna.K.Chaitanya@shell.com\",\r\n"
				+ "            \"_login\": \"1Krishna.K.Chaitanya@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 758\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:38\",\r\n"
				+ "            \"last_name\": \"Luuk\",\r\n"
				+ "            \"internal_id\": \"SNLBOC\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Bosma\",\r\n"
				+ "            \"email\": \"1luuk.bosma@shell.com\",\r\n"
				+ "            \"_login\": \"1luuk.bosma@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 759\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:38\",\r\n"
				+ "            \"last_name\": \"Mazur\",\r\n"
				+ "            \"internal_id\": \"PLPMAY\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Piotr\",\r\n"
				+ "            \"email\": \"1p.mazur@shell.com\",\r\n"
				+ "            \"_login\": \"1p.mazur@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 760\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:38\",\r\n"
				+ "            \"last_name\": \"Chimirala\",\r\n"
				+ "            \"internal_id\": \"NLPCI6\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Pradeepa\",\r\n"
				+ "            \"email\": \"1Pradeepa.Chimirala@shell.com\",\r\n"
				+ "            \"_login\": \"1Pradeepa.Chimirala@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 761\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:38\",\r\n"
				+ "            \"last_name\": \"Bilby\",\r\n"
				+ "            \"internal_id\": \"NLRBJ9\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Richard\",\r\n"
				+ "            \"email\": \"1R.Bilby@shell.com\",\r\n"
				+ "            \"_login\": \"1R.Bilby@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 762\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 10 2025 08:25:00\",\r\n"
				+ "            \"last_name\": \"Sedek\",\r\n"
				+ "            \"internal_id\": \"MYRSE4\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Rozita\",\r\n"
				+ "            \"email\": \"1Rozita.Sedek@shell.com\",\r\n"
				+ "            \"_login\": \"1Rozita.Sedek@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 764\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 21 2025 16:10:50\",\r\n"
				+ "            \"last_name\": \"Mohanty\",\r\n"
				+ "            \"internal_id\": \"INSOOP\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Swayamprava\",\r\n"
				+ "            \"email\": \"1Swayamprava.Mohanty@shell.com\",\r\n"
				+ "            \"_login\": \"1Swayamprava.Mohanty@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 765\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 10 2025 08:25:00\",\r\n"
				+ "            \"last_name\": \"Wrzosek\",\r\n"
				+ "            \"internal_id\": \"PLSWR0\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Szymon\",\r\n"
				+ "            \"email\": \"1Szymon.Wrzosek@shell.com\",\r\n"
				+ "            \"_login\": \"1Szymon.Wrzosek@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 766\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:39\",\r\n"
				+ "            \"last_name\": \"Dziadosz-Czarnecki\",\r\n"
				+ "            \"internal_id\": \"PLZDZ0\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Zbigniew\",\r\n"
				+ "            \"email\": \"1Zbigniew.Dziadosz@shell.com\",\r\n"
				+ "            \"_login\": \"1Zbigniew.Dziadosz@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 767\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:39\",\r\n"
				+ "            \"last_name\": \"B\",\r\n"
				+ "            \"internal_id\": \"INHBBJ\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Hemalatha \",\r\n"
				+ "            \"email\": \"1Hemalatha.B@shell.com\",\r\n"
				+ "            \"_login\": \"1Hemalatha.B@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 768\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:39\",\r\n"
				+ "            \"last_name\": \"Shustov\",\r\n"
				+ "            \"internal_id\": \"GBDSIW\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Dmitry\",\r\n"
				+ "            \"email\": \"1Dmitry.Shustov@shell.com\",\r\n"
				+ "            \"_login\": \"1Dmitry.Shustov@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 769\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:39\",\r\n"
				+ "            \"last_name\": \"Manjunath\",\r\n"
				+ "            \"internal_id\": \"INMMDA\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Mamatha\",\r\n"
				+ "            \"email\": \"1M.Manjunath@shell.com\",\r\n"
				+ "            \"_login\": \"1M.Manjunath@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 770\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 16 2025 16:19:43\",\r\n"
				+ "            \"last_name\": \"Support\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Agiloft\",\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"_login\": \"1support\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 771\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 19 2025 10:22:36\",\r\n"
				+ "            \"last_name\": \"Kundu\",\r\n"
				+ "            \"internal_id\": \"INALCQ\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Amitava\",\r\n"
				+ "            \"email\": \"1Amitava.Kundu@shell.com\",\r\n"
				+ "            \"_login\": \"1Amitava.Kundu@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 777\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 21 2025 16:11:55\",\r\n"
				+ "            \"last_name\": \"Sarker\",\r\n"
				+ "            \"internal_id\": \"INSXZQ\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Santanu\",\r\n"
				+ "            \"email\": \"1Santanu.Sarker@shell.com\",\r\n"
				+ "            \"_login\": \"1Santanu.Sarker@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 778\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 21 2025 16:11:49\",\r\n"
				+ "            \"last_name\": \"Chinchwadkar\",\r\n"
				+ "            \"internal_id\": \"INNCKW\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Nishad\",\r\n"
				+ "            \"email\": \"1N.Chinchwadkar@shell.com\",\r\n"
				+ "            \"_login\": \"1N.Chinchwadkar@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 779\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 21 2025 16:11:43\",\r\n"
				+ "            \"last_name\": \"Velu\",\r\n"
				+ "            \"internal_id\": \"INVVGL\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Vishnu\",\r\n"
				+ "            \"email\": \"1Vishnu.Velu@shell.com\",\r\n"
				+ "            \"_login\": \"1Vishnu.Velu@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 780\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 02 2025 10:59:20\",\r\n"
				+ "            \"last_name\": \"User\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"DocuSign\",\r\n"
				+ "            \"email\": \"1PT-CLM-Docusign-Test@shell.com\",\r\n"
				+ "            \"_login\": \"1PT-CLM-Docusign-Test@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 782\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:39\",\r\n"
				+ "            \"last_name\": \"Gupta\",\r\n"
				+ "            \"internal_id\": \"INRGX6\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Reeta\",\r\n"
				+ "            \"email\": \"1reeta.gupta@shell.com\",\r\n"
				+ "            \"_login\": \"1reeta.gupta@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 783\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:39\",\r\n"
				+ "            \"last_name\": \"Adya Jahagirdar\",\r\n"
				+ "            \"internal_id\": \"INSADL\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Srish\",\r\n"
				+ "            \"email\": \"1srish.adyajahagirdar@shell.com\",\r\n"
				+ "            \"_login\": \"1srish.adyajahagirdar@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 784\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 19 2025 13:22:17\",\r\n"
				+ "            \"last_name\": \"Perftestit\",\r\n"
				+ "            \"internal_id\": \"NLE754\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"0001\",\r\n"
				+ "            \"email\": \"1Perftestit-0001-T@shell.com\",\r\n"
				+ "            \"_login\": \"1Perftestit-0001-T@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 786\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"May 12 2025 19:44:39\",\r\n"
				+ "            \"last_name\": \"Danannavar\",\r\n"
				+ "            \"internal_id\": \"INVDBN\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Vikram\",\r\n"
				+ "            \"email\": \"1Vikram.Danannavar@shell.com\",\r\n"
				+ "            \"_login\": \"1Vikram.Danannavar@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 787\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 19 2025 13:22:17\",\r\n"
				+ "            \"last_name\": \"TCoE\",\r\n"
				+ "            \"internal_id\": null,\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Test0001\",\r\n"
				+ "            \"email\": \"1TCoE-Test0001-t@ShellCorp.onmicrosoft.com\",\r\n"
				+ "            \"_login\": \"1TCoE-Test0001-t@ShellCorp.onmicrosoft.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 788\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jun 26 2025 08:36:38\",\r\n"
				+ "            \"last_name\": \"Wagmodi\",\r\n"
				+ "            \"internal_id\": \"INSXHC\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": null,\r\n"
				+ "            \"first_name\": \"Suresh\",\r\n"
				+ "            \"email\": \"1s.wagmodi@shell.com\",\r\n"
				+ "            \"_login\": \"1Wagmodi, Suresh SOMIBM-IBM\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 789\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jul 08 2025 08:36:31\",\r\n"
				+ "            \"last_name\": \"Agrawal\",\r\n"
				+ "            \"internal_id\": \"INKAG5\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Kopal\",\r\n"
				+ "            \"email\": \"1Kopal.Agrawal@shell.com\",\r\n"
				+ "            \"_login\": \"1Kopal.Agrawal@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 790\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"date_updated\": \"Jul 08 2025 16:42:22\",\r\n"
				+ "            \"last_name\": \"Begum\",\r\n"
				+ "            \"internal_id\": \"INRBMO\",\r\n"
				+ "            \"working_status\": \"Working\",\r\n"
				+ "            \"current_roles\": [\r\n"
				+ "                \"Contract Creator\",\r\n"
				+ "                \"Business Admin\"\r\n"
				+ "            ],\r\n"
				+ "            \"first_name\": \"Rizwana\",\r\n"
				+ "            \"email\": \"1Rizwana.Begum@shell.com\",\r\n"
				+ "            \"_login\": \"1Rizwana.Begum@shell.com\",\r\n"
				+ "            \"employment_status\": \"Active\",\r\n"
				+ "            \"id\": 791\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"pagination_details\": {\r\n"
				+ "        \"has_more_records\": false,\r\n"
				+ "        \"next_id_to_use\": 0\r\n"
				+ "    }\r\n"
				+ "}";
		return data;
	}
}
