package com.iamsystem.service;

import java.util.Map;

import org.springframework.stereotype.Service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

@Service
public class HighRadiusDevService {

	
	public Map<String,Object> getPage1Accounts(){
		Map<String,Object> returnResult = null;
		String data = getAccountData();
		returnResult = convertStringToMap(data);
		return returnResult;
	}
	
	public Map<String, Object> convertStringToMap(String data) {
		ObjectMapper mapper = new ObjectMapper();
		Map<String, Object> map = null;
		try {
			map = mapper.readValue(data, new TypeReference<Map<String, Object>>() {});
		} catch (JsonMappingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return map;
	}

	private String getAccountData() {
		String data ="{\r\n"
				+ "    \"schemas\": [\r\n"
				+ "        \"urn:ietf:params:scim:api:messages:2.0:ListResponse\"\r\n"
				+ "    ],\r\n"
				+ "    \"totalResults\": 50,\r\n"
				+ "    \"itemsPerPage\": 20,\r\n"
				+ "    \"startIndex\": 1,\r\n"
				+ "    \"Resources\": [\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-7286-9719cd07-889b-3f6891e084c1\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-08-06T05:31:23Z\",\r\n"
				+ "                \"lastModified\": \"2025-08-06T05:46:15Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-7286-9719cd07-889b-3f6891e084c1\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"SSSCMLA-Retailer-Billing-SK-Bill-to-Cash@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"SK01 Functional Mail Box\",\r\n"
				+ "                \"familyName\": \"Functional Mail Box\",\r\n"
				+ "                \"givenName\": \"SK01\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"SK01 Functional Mail Box\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"SSSCMLA-Retailer-Billing-SK-Bill-to-Cash@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-7286-5f29bc4d-b017-7b196583791d\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-08-06T05:29:50Z\",\r\n"
				+ "                \"lastModified\": \"2025-08-06T05:46:02Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-7286-5f29bc4d-b017-7b196583791d\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"SSSCMLA-Retailer-Billing-CZ-Bill-to-Cash@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"CZ Functional Mail Box\",\r\n"
				+ "                \"familyName\": \"Functional Mail Box\",\r\n"
				+ "                \"givenName\": \"CZ\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"CZ Functional Mail Box\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"SSSCMLA-Retailer-Billing-CZ-Bill-to-Cash@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-5259-9b8dbe0e-9491-f7eb5ffcfb64\",\r\n"
				+ "            \"externalId\": \"12345\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-06-26T06:48:46Z\",\r\n"
				+ "                \"lastModified\": \"2025-06-26T06:48:46Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-5259-9b8dbe0e-9491-f7eb5ffcfb64\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"farooq@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"farooq Mohammed\",\r\n"
				+ "                \"familyName\": \"Mohammed\",\r\n"
				+ "                \"givenName\": \"farooq\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"farooq Mohammed\",\r\n"
				+ "            \"title\": \"Mr\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"farooq@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ],\r\n"
				+ "            \"phoneNumbers\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"1234567890\",\r\n"
				+ "                    \"type\": \"work\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-5255-21615546-bc63-7df0c6d7ef9f\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-06-26T06:16:43Z\",\r\n"
				+ "                \"lastModified\": \"2025-08-01T09:08:19Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-5255-21615546-bc63-7df0c6d7ef9f\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"bhanu@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"bhanuamara kiran\",\r\n"
				+ "                \"familyName\": \"kiran\",\r\n"
				+ "                \"givenName\": \"bhanuamara\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"bhanuamara kiran\",\r\n"
				+ "            \"title\": \"Mr\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"bhanu@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ],\r\n"
				+ "            \"phoneNumbers\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"1234567890\",\r\n"
				+ "                    \"type\": \"work\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-3c81-6bea7342-9ebb-efb03f80c4ac\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-05-29T11:38:21Z\",\r\n"
				+ "                \"lastModified\": \"2025-05-29T11:38:21Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-3c81-6bea7342-9ebb-efb03f80c4ac\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"shell.automationviewer@highradius.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Shell automationviewer\",\r\n"
				+ "                \"familyName\": \"automationviewer\",\r\n"
				+ "                \"givenName\": \"Shell\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Shell automationviewer\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"shell.automationviewer@highradius.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-3c7c-c7953181-9ebb-3796ecb98b24\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-05-29T11:05:07Z\",\r\n"
				+ "                \"lastModified\": \"2025-07-22T09:06:06Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-3c7c-c7953181-9ebb-3796ecb98b24\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"shell.automationadmin@highradius.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Shell automationadmin\",\r\n"
				+ "                \"familyName\": \"automationadmin\",\r\n"
				+ "                \"givenName\": \"Shell\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Shell automationadmin\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": false,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"shell.automationadmin@highradius.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-3baf-a89dba5f-83c0-0b296fd2622c\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-05-28T10:36:48Z\",\r\n"
				+ "                \"lastModified\": \"2025-07-22T06:59:22Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-3baf-a89dba5f-83c0-0b296fd2622c\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"shell.automationmanager@highradius.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Shell automationmanager\",\r\n"
				+ "                \"familyName\": \"automationmanager\",\r\n"
				+ "                \"givenName\": \"Shell\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Shell automationmanager\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"shell.automationmanager@highradius.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-3a0c-9d3b8f1e-96f9-417ea3d2f213\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-05-26T08:37:10Z\",\r\n"
				+ "                \"lastModified\": \"2025-05-26T08:37:10Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-3a0c-9d3b8f1e-96f9-417ea3d2f213\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"Jayzel.Fiedalan@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Jayzel Fiedalan\",\r\n"
				+ "                \"familyName\": \"Fiedalan\",\r\n"
				+ "                \"givenName\": \"Jayzel\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Jayzel Fiedalan\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"Jayzel.Fiedalan@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-3a0c-9cad0abd-96f9-ad90431ec604\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-05-26T08:37:09Z\",\r\n"
				+ "                \"lastModified\": \"2025-05-26T08:37:09Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-3a0c-9cad0abd-96f9-ad90431ec604\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"Stephen.Pasia@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Stephen Pasia\",\r\n"
				+ "                \"familyName\": \"Pasia\",\r\n"
				+ "                \"givenName\": \"Stephen\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Stephen Pasia\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"Stephen.Pasia@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-3a0b-d1157136-a283-4daed886f7de\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-05-26T08:31:28Z\",\r\n"
				+ "                \"lastModified\": \"2025-05-26T08:31:28Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-3a0b-d1157136-a283-4daed886f7de\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"Dolly.Celi@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Dolly Celi\",\r\n"
				+ "                \"familyName\": \"Celi\",\r\n"
				+ "                \"givenName\": \"Dolly\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Dolly Celi\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"Dolly.Celi@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-2c16-a0f02281-aae8-13ad2caf0bd9\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-05-08T14:13:35Z\",\r\n"
				+ "                \"lastModified\": \"2025-07-08T10:10:22Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-2c16-a0f02281-aae8-13ad2caf0bd9\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"shell.automation@highradius.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Shell Automation\",\r\n"
				+ "                \"familyName\": \"Automation\",\r\n"
				+ "                \"givenName\": \"Shell\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Shell Automation\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"shell.automation@highradius.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-25c6-c4db8b2d-a3af-334d504da38e\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-04-30T13:26:49Z\",\r\n"
				+ "                \"lastModified\": \"2025-04-30T13:26:49Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-25c6-c4db8b2d-a3af-334d504da38e\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"P.Prathiksha@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Prathiksha P\",\r\n"
				+ "                \"familyName\": \"P\",\r\n"
				+ "                \"givenName\": \"Prathiksha\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Prathiksha P\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"P.Prathiksha@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-1f81-f57d5885-90d8-dd2ec51db90d\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-04-22T13:59:08Z\",\r\n"
				+ "                \"lastModified\": \"2025-04-22T13:59:08Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-1f81-f57d5885-90d8-dd2ec51db90d\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"Richelle.Orosco@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Richelle Rene Orosco\",\r\n"
				+ "                \"familyName\": \"Orosco\",\r\n"
				+ "                \"givenName\": \"Richelle Rene\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Richelle Rene Orosco\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"Richelle.Orosco@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-1f81-c3e4f6d2-bbcd-37668199c0c1\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-04-22T13:57:45Z\",\r\n"
				+ "                \"lastModified\": \"2025-04-22T13:57:45Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-1f81-c3e4f6d2-bbcd-37668199c0c1\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"Cherry-Anne.Mallari@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Cherry Anne Mallari\",\r\n"
				+ "                \"familyName\": \"Mallari\",\r\n"
				+ "                \"givenName\": \"Cherry Anne\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Cherry Anne Mallari\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"Cherry-Anne.Mallari@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-1f81-a1969d91-bbcd-3bc24d562d4e\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-04-22T13:56:47Z\",\r\n"
				+ "                \"lastModified\": \"2025-04-22T13:56:47Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-1f81-a1969d91-bbcd-3bc24d562d4e\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"A.Mojares@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Alyanna Mariel Mojares\",\r\n"
				+ "                \"familyName\": \"Mojares\",\r\n"
				+ "                \"givenName\": \"Alyanna Mariel\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Alyanna Mariel Mojares\",\r\n"
				+ "            \"title\": \"\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"A.Mojares@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-1ac0-6a115914-90d8-7b1f8b41347d\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-04-16T12:43:36Z\",\r\n"
				+ "                \"lastModified\": \"2025-04-16T12:43:36Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-1ac0-6a115914-90d8-7b1f8b41347d\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"Patricia-Ann.Canada@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Patricia Ann Canada\",\r\n"
				+ "                \"familyName\": \"Canada\",\r\n"
				+ "                \"givenName\": \"Patricia Ann\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Patricia Ann Canada\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"Patricia-Ann.Canada@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-1ac0-699d3a83-90d8-c5fc5fedbf1e\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-04-16T12:43:36Z\",\r\n"
				+ "                \"lastModified\": \"2025-06-09T11:08:30Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-1ac0-699d3a83-90d8-c5fc5fedbf1e\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"N.Jacoba@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Nneka Rae Janelle Jacoba\",\r\n"
				+ "                \"familyName\": \"Jacoba\",\r\n"
				+ "                \"givenName\": \"Nneka Rae Janelle\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Nneka Rae Janelle Jacoba\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"N.Jacoba@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-1ac0-69361442-90d8-d33440f04e8d\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-04-16T12:43:35Z\",\r\n"
				+ "                \"lastModified\": \"2025-04-16T12:43:35Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-1ac0-69361442-90d8-d33440f04e8d\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"Nick-John.Albina@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Nick John Albina\",\r\n"
				+ "                \"familyName\": \"Albina\",\r\n"
				+ "                \"givenName\": \"Nick John\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Nick John Albina\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"Nick-John.Albina@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-1ac0-68d77981-90d8-d15c1acd9e37\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-04-16T12:43:34Z\",\r\n"
				+ "                \"lastModified\": \"2025-05-28T12:43:37Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-1ac0-68d77981-90d8-d15c1acd9e37\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"M.Baysic@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Matthew Edison Baysic\",\r\n"
				+ "                \"familyName\": \"Baysic\",\r\n"
				+ "                \"givenName\": \"Matthew Edison\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Matthew Edison Baysic\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"M.Baysic@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"schemas\": [\r\n"
				+ "                \"urn:ietf:params:scim:schemas:extension:highradius:User\"\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"11f0-1ac0-67d6d25f-90d8-2180be3a8ec5\",\r\n"
				+ "            \"meta\": {\r\n"
				+ "                \"resourceType\": \"User\",\r\n"
				+ "                \"created\": \"2025-04-16T12:43:33Z\",\r\n"
				+ "                \"lastModified\": \"2025-04-16T12:43:33Z\",\r\n"
				+ "                \"location\": \"https://sb1-shell-uat.highradius.com/iam/api/scim/Users/11f0-1ac0-67d6d25f-90d8-2180be3a8ec5\"\r\n"
				+ "            },\r\n"
				+ "            \"userName\": \"K.Albitos@shell.com\",\r\n"
				+ "            \"name\": {\r\n"
				+ "                \"formatted\": \"Karl Angelo Joshua Albitos\",\r\n"
				+ "                \"familyName\": \"Albitos\",\r\n"
				+ "                \"givenName\": \"Karl Angelo Joshua\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"Karl Angelo Joshua Albitos\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"emails\": [\r\n"
				+ "                {\r\n"
				+ "                    \"value\": \"K.Albitos@shell.com\",\r\n"
				+ "                    \"primary\": true\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		
		return data;
	}
}
